name: 'Deploy to vercel on merge'
on:
  push:
    branches:
      - 'main'
jobs:
  build_and_deploy:
    permissions: 'write-all'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Install vercel'
        run: 'npm install -g vercel'

      - name: 'Link Vercel project'
        run: |
          vercel link \
            --token ${{ secrets.VERCEL_TOKEN }} \
            --scope ${{ secrets.VERCEL_ORG_ID }} \
            --yes

      - name: Deploy to Vercel
        id: 'vercel-deploy'
        run: |
          DEPLOY_URL=$(vercel deploy \
            --token ${{ secrets.VERCEL_TOKEN}} \
            --scope ${{ secrets.VERCEL_ORG_ID}} \
            --prod \
            --yes)
